-- =========================================================
-- TABLA: categorias
-- =========================================================
-- Almacena las categorías usadas para clasificar productos.
CREATE TABLE categorias (
                            id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            nombre VARCHAR(100) NOT NULL,
                            CONSTRAINT uk_categorias_nombre UNIQUE (nombre)
);

-- Optimiza las búsquedas por nombre de categoría.
CREATE INDEX idx_categorias_nombre
    ON categorias (nombre);

-- =========================================================
-- TABLA: canales_venta
-- =========================================================
-- Registra los canales de venta disponibles para los productos.
CREATE TABLE canales_venta (
                               id_canal_venta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               nombre VARCHAR(50) NOT NULL,
                               CONSTRAINT uk_canales_venta_nombre UNIQUE (nombre)
);

-- Mejora el rendimiento en consultas por nombre de canal.
CREATE INDEX idx_canales_venta_nombre
    ON canales_venta (nombre);

-- =========================================================
-- TABLA: usuarios
-- =========================================================
-- Guarda los usuarios del sistema, incluyendo sus credenciales y rol.
CREATE TABLE usuarios (
                          id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nombre VARCHAR(50) NOT NULL,
                          apellido VARCHAR(50) NOT NULL,
                          username VARCHAR(50) NOT NULL,
                          password VARCHAR(255) NOT NULL,
                          activo BOOLEAN NOT NULL DEFAULT TRUE,
                          rol VARCHAR(30) NOT NULL,
                          CONSTRAINT uk_usuarios_username UNIQUE (username)
);

-- Acelera búsquedas por nombre de usuario.
CREATE INDEX idx_usuarios_username
    ON usuarios (username);

-- Facilita filtrados por rol de usuario.
CREATE INDEX idx_usuarios_rol
    ON usuarios (rol);

-- =========================================================
-- TABLA: productos
-- =========================================================
-- Almacena los productos del catálogo y sus precios.
CREATE TABLE productos (
                           id_producto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           id_categoria INTEGER NOT NULL,
                           nombre VARCHAR(100) NOT NULL,
                           imagen VARCHAR(255),
                           precio_minorista NUMERIC(10,2) NOT NULL DEFAULT 0.00,
                           precio_mayorista NUMERIC(10,2) NOT NULL DEFAULT 0.00,
                           cantidad_minima_mayorista INTEGER NOT NULL DEFAULT 0,
                           activo BOOLEAN NOT NULL DEFAULT TRUE,
                           tiene_variantes BOOLEAN NOT NULL DEFAULT TRUE,

                           CONSTRAINT fk_productos_categoria
                               FOREIGN KEY (id_categoria)
                                   REFERENCES categorias (id_categoria)
                                   ON UPDATE CASCADE
                                   ON DELETE RESTRICT,

                           CONSTRAINT chk_productos_precio_minorista
                               CHECK (precio_minorista >= 0),

                           CONSTRAINT chk_productos_precio_mayorista
                               CHECK (precio_mayorista >= 0),

                           CONSTRAINT chk_productos_cantidad_minima_mayorista
                               CHECK (cantidad_minima_mayorista >= 0)
);

-- Optimiza búsquedas por nombre de producto.
CREATE INDEX idx_productos_nombre
    ON productos (nombre);

-- Mejora el acceso por categoría asociada.
CREATE INDEX idx_productos_categoria
    ON productos (id_categoria);

-- =========================================================
-- TABLA: variantes_producto
-- =========================================================
-- Representa variantes de un producto, como SKU o código de barras.
CREATE TABLE variantes_producto (
                                    id_variante INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    id_producto INTEGER NOT NULL,
                                    codigo_barras VARCHAR(50),
                                    codigo_interno VARCHAR(50) NOT NULL,
                                    nombre_variante VARCHAR(100) NOT NULL,
                                    activo BOOLEAN NOT NULL DEFAULT TRUE,

                                    CONSTRAINT fk_variantes_producto_producto
                                        FOREIGN KEY (id_producto)
                                            REFERENCES productos (id_producto)
                                            ON UPDATE CASCADE
                                            ON DELETE RESTRICT,

                                    CONSTRAINT uk_variantes_producto_codigo_barras
                                        UNIQUE (codigo_barras),

                                    CONSTRAINT uk_variantes_producto_codigo_interno
                                        UNIQUE (codigo_interno)
);

-- Acelera consultas por producto padre.
CREATE INDEX idx_variantes_producto_producto
    ON variantes_producto (id_producto);

-- Optimiza búsquedas por código de barras.
CREATE INDEX idx_variantes_producto_codigo_barras
    ON variantes_producto (codigo_barras);

-- =========================================================
-- TABLA: productos_canales
-- =========================================================
-- Relaciona productos con canales de venta y define reglas de mayorista.
CREATE TABLE productos_canales (
                                   id_producto_canal INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   id_producto INTEGER NOT NULL,
                                   id_canal_venta INTEGER NOT NULL,
                                   limite_mayorista INTEGER NOT NULL DEFAULT 1,

                                   CONSTRAINT fk_productos_canales_producto
                                       FOREIGN KEY (id_producto)
                                           REFERENCES productos (id_producto)
                                           ON UPDATE CASCADE
                                           ON DELETE RESTRICT,

                                   CONSTRAINT fk_productos_canales_canal
                                       FOREIGN KEY (id_canal_venta)
                                           REFERENCES canales_venta (id_canal_venta)
                                           ON UPDATE CASCADE
                                           ON DELETE RESTRICT,

                                   CONSTRAINT uk_productos_canales_producto_canal UNIQUE (id_producto, id_canal_venta),

                                   CONSTRAINT chk_productos_canales_limite_mayorista
                                       CHECK (limite_mayorista >= 1)
);

-- Optimiza búsquedas por producto asociado.
CREATE INDEX idx_productos_canales_producto
    ON productos_canales (id_producto);

-- Optimiza búsquedas por canal de venta asociado.
CREATE INDEX idx_productos_canales_canal
    ON productos_canales (id_canal_venta);

-- =========================================================
-- TABLA: stock
-- =========================================================
-- Controla el inventario disponible por variante y canal de venta.
CREATE TABLE stock (
                       id_stock INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       id_variante INTEGER NOT NULL,
                       id_canal_venta INTEGER NOT NULL,
                       cantidad_disponible INTEGER NOT NULL DEFAULT 0,
                       stock_minimo INTEGER NOT NULL DEFAULT 0,
                       estado VARCHAR(30) NOT NULL,

                       CONSTRAINT fk_stock_variante
                           FOREIGN KEY (id_variante)
                               REFERENCES variantes_producto (id_variante)
                               ON UPDATE CASCADE
                               ON DELETE RESTRICT,

                       CONSTRAINT fk_stock_canal
                           FOREIGN KEY (id_canal_venta)
                               REFERENCES canales_venta (id_canal_venta)
                               ON UPDATE CASCADE
                               ON DELETE RESTRICT,

                       CONSTRAINT uk_stock_variante_canal UNIQUE (id_variante, id_canal_venta),

                       CONSTRAINT chk_stock_cantidad_disponible
                           CHECK (cantidad_disponible >= 0),

                       CONSTRAINT chk_stock_minimo
                           CHECK (stock_minimo >= 0)
);

-- Optimiza búsquedas por variante de producto.
CREATE INDEX idx_stock_variante
    ON stock (id_variante);

-- Optimiza búsquedas por canal de venta.
CREATE INDEX idx_stock_canal
    ON stock (id_canal_venta);

