-- =========================================================
-- TABLA: cajas
-- =========================================================
-- Representa una sesión de caja abierta por un usuario.
CREATE TABLE cajas (
                       id_caja INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       id_usuario INTEGER NOT NULL,
                       fecha_apertura TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       fecha_cierre TIMESTAMPTZ,
                       monto_inicial NUMERIC(10,2) NOT NULL DEFAULT 0.00,
                       monto_final NUMERIC(10,2),
                       saldo_esperado NUMERIC(10,2),
                       estado VARCHAR(30) NOT NULL DEFAULT 'ABIERTA',

                       CONSTRAINT fk_cajas_usuario
                           FOREIGN KEY (id_usuario)
                               REFERENCES usuarios(id_usuario)
                               ON UPDATE CASCADE
                               ON DELETE RESTRICT,

                       CONSTRAINT chk_cajas_monto_inicial
                           CHECK (monto_inicial >= 0)
);

CREATE INDEX idx_cajas_usuario
    ON cajas (id_usuario);

CREATE INDEX idx_cajas_estado
    ON cajas (estado);

CREATE INDEX idx_cajas_fecha_apertura
    ON cajas (fecha_apertura);

-- =========================================================
-- TABLA: ventas
-- =========================================================
-- Registra las ventas realizadas y su estado de proceso.
CREATE TABLE ventas (
                        id_venta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        id_caja INTEGER NOT NULL,
                        id_usuario INTEGER NOT NULL,
                        fecha_hora TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        subtotal NUMERIC(10,2) NOT NULL DEFAULT 0.00,
                        descuento NUMERIC(10,2) NOT NULL DEFAULT 0.00,
                        total NUMERIC(10,2) NOT NULL DEFAULT 0.00,
                        estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',

                        CONSTRAINT fk_ventas_caja
                            FOREIGN KEY (id_caja)
                                REFERENCES cajas (id_caja)
                                ON UPDATE CASCADE
                                ON DELETE RESTRICT,

                        CONSTRAINT fk_ventas_usuario
                            FOREIGN KEY (id_usuario)
                                REFERENCES usuarios (id_usuario)
                                ON UPDATE CASCADE
                                ON DELETE RESTRICT,

                        CONSTRAINT chk_ventas_subtotal
                            CHECK (subtotal >= 0),

                        CONSTRAINT chk_ventas_descuento
                            CHECK (descuento >= 0),

                        CONSTRAINT chk_ventas_total
                            CHECK (total >= 0)
);

CREATE INDEX idx_ventas_caja
    ON ventas (id_caja);

-- Optimiza filtros por fecha y hora de venta.
CREATE INDEX idx_ventas_fecha_hora
    ON ventas (fecha_hora);

-- Acelera consultas por usuario responsable de la venta.
CREATE INDEX idx_ventas_usuario
    ON ventas (id_usuario);

-- Facilita búsquedas por estado de la venta.
CREATE INDEX idx_ventas_estado
    ON ventas (estado);

-- =========================================================
-- TABLA: detalle_ventas
-- =========================================================
-- Guarda los productos incluidos en cada venta con su cantidad y precio.
CREATE TABLE detalle_ventas (
                                id_detalle_venta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                id_venta INTEGER NOT NULL,
                                id_variante INTEGER NOT NULL,
                                cantidad INTEGER NOT NULL,
                                precio_unitario NUMERIC(10,2) NOT NULL DEFAULT 0.00,
                                subtotal NUMERIC(10,2) NOT NULL DEFAULT 0.00,

                                CONSTRAINT fk_detalle_ventas_venta
                                    FOREIGN KEY (id_venta)
                                        REFERENCES ventas (id_venta)
                                        ON UPDATE CASCADE
                                        ON DELETE CASCADE,

                                CONSTRAINT fk_detalle_ventas_variante
                                    FOREIGN KEY (id_variante)
                                        REFERENCES variantes_producto (id_variante)
                                        ON UPDATE CASCADE
                                        ON DELETE RESTRICT,

                                CONSTRAINT chk_detalle_ventas_cantidad
                                    CHECK (cantidad > 0),

                                CONSTRAINT chk_detalle_ventas_precio_unitario
                                    CHECK (precio_unitario >= 0),

                                CONSTRAINT chk_detalle_ventas_subtotal
                                    CHECK (subtotal >= 0)
);

-- Optimiza consultas por venta asociada.
CREATE INDEX idx_detalle_ventas_venta
    ON detalle_ventas (id_venta);

-- Optimiza consultas por variante vendida.
CREATE INDEX idx_detalle_ventas_variante
    ON detalle_ventas (id_variante);

-- =========================================================
-- TABLA: pagos
-- =========================================================
-- Registra los pagos asociados a cada venta.
CREATE TABLE pagos (
                       id_pago INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       id_venta INTEGER NOT NULL,
                       medio_pago VARCHAR(30) NOT NULL,
                       importe NUMERIC(10,2) NOT NULL DEFAULT 0.00,

                       CONSTRAINT fk_pagos_venta
                           FOREIGN KEY (id_venta)
                               REFERENCES ventas (id_venta)
                               ON UPDATE CASCADE
                               ON DELETE CASCADE,

                       CONSTRAINT chk_pagos_importe
                           CHECK (importe >= 0)
);

-- Mejora el acceso por venta asociada.
CREATE INDEX idx_pagos_venta
    ON pagos (id_venta);

-- Facilita filtros por medio de pago.
CREATE INDEX idx_pagos_medio_pago
    ON pagos (medio_pago);


-- =========================================================
-- TABLA: movimientos_caja
-- =========================================================
-- Registra todos los movimientos monetarios realizados en una caja.
CREATE TABLE movimientos_caja (
                                  id_movimiento_caja INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  id_caja INTEGER NOT NULL,
                                  fecha_hora TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  tipo_movimiento VARCHAR(30) NOT NULL,
                                  importe NUMERIC(10,2) NOT NULL,

                                  CONSTRAINT fk_movimientos_caja_caja
                                      FOREIGN KEY (id_caja)
                                          REFERENCES cajas(id_caja)
                                          ON UPDATE CASCADE
                                          ON DELETE CASCADE
);

CREATE INDEX idx_movimientos_caja_caja
    ON movimientos_caja (id_caja);

CREATE INDEX idx_movimientos_caja_fecha_hora
    ON movimientos_caja (fecha_hora);

CREATE INDEX idx_movimientos_caja_tipo
    ON movimientos_caja (tipo_movimiento);


-- =========================================================
-- TABLA: movimientos_stock
-- =========================================================
-- Registra los cambios de inventario y su historial.
CREATE TABLE movimientos_stock (
                                   id_movimiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   id_usuario INTEGER NOT NULL,
                                   id_stock INTEGER NOT NULL,
                                   fecha_hora TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   tipo_movimiento VARCHAR(30) NOT NULL,
                                   cantidad INTEGER NOT NULL,
                                   stock_anterior INTEGER NOT NULL,
                                   stock_resultante INTEGER NOT NULL,
                                   motivo VARCHAR(255),

                                   CONSTRAINT fk_movimientos_stock_usuario
                                       FOREIGN KEY (id_usuario)
                                           REFERENCES usuarios (id_usuario)
                                           ON UPDATE CASCADE
                                           ON DELETE RESTRICT,

                                   CONSTRAINT fk_movimientos_stock_stock
                                       FOREIGN KEY (id_stock)
                                           REFERENCES stock (id_stock)
                                           ON UPDATE CASCADE
                                           ON DELETE RESTRICT,

                                   CONSTRAINT chk_movimientos_stock_cantidad
                                       CHECK (cantidad > 0)
);

-- Optimiza consultas por fecha y hora del movimiento.
CREATE INDEX idx_movimientos_stock_fecha_hora
    ON movimientos_stock (fecha_hora);

-- Acelera búsquedas por usuario que realizó el movimiento.
CREATE INDEX idx_movimientos_stock_usuario
    ON movimientos_stock (id_usuario);

-- Mejora el acceso por stock asociado.
CREATE INDEX idx_movimientos_stock_stock
    ON movimientos_stock (id_stock);

-- Facilita filtros por tipo de movimiento.
CREATE INDEX idx_movimientos_stock_tipo_movimiento
    ON movimientos_stock (tipo_movimiento);