-- =========================================================
-- SISTEMA PDV
-- Archivo: schema.sql
-- Motor: PostgreSQL 18.4
-- =========================================================

-- =========================================================
-- LIMPIEZA DE OBJETOS EXISTENTES
-- =========================================================
-- Elimina objetos previos para recrear el esquema de forma limpia.
DROP TABLE IF EXISTS movimientos_stock CASCADE;
DROP TABLE IF EXISTS movimientos_caja CASCADE;
DROP TABLE IF EXISTS cajas CASCADE;
DROP TABLE IF EXISTS pagos CASCADE;
DROP TABLE IF EXISTS detalle_ventas CASCADE;
DROP TABLE IF EXISTS ventas CASCADE;
DROP TABLE IF EXISTS stock CASCADE;
DROP TABLE IF EXISTS productos_canales CASCADE;
DROP TABLE IF EXISTS variantes_producto CASCADE;
DROP TABLE IF EXISTS productos CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS canales_venta CASCADE;
DROP TABLE IF EXISTS categorias CASCADE;

-- Elimina los tipos enum creados previamente para evitar conflictos.
DROP TYPE IF EXISTS rol_usuario CASCADE;
DROP TYPE IF EXISTS estado_venta CASCADE;
DROP TYPE IF EXISTS medio_pago_enum CASCADE;
DROP TYPE IF EXISTS tipo_movimiento_enum CASCADE;
DROP TYPE IF EXISTS estado_caja CASCADE;
DROP TYPE IF EXISTS tipo_movimiento_caja_enum CASCADE;

-- =========================================================
-- TIPOS ENUM
-- =========================================================
-- Define los roles válidos para los usuarios del sistema.
CREATE TYPE rol_usuario AS ENUM ('ADMINISTRADOR', 'CAJERO');

-- Define los estados posibles de una venta.
CREATE TYPE estado_venta AS ENUM ('PENDIENTE', 'COMPLETADA', 'CANCELADA');

-- Define los medios de pago soportados.
CREATE TYPE medio_pago_enum AS ENUM ('EFECTIVO', 'TRANSFERENCIA');

-- Define los tipos de movimiento de inventario.
CREATE TYPE tipo_movimiento_enum AS ENUM ('ENTRADA', 'SALIDA', 'AJUSTE');

CREATE TYPE estado_caja AS ENUM ('ABIERTA', 'CERRADA');

CREATE TYPE tipo_movimiento_caja_enum AS ENUM ('APERTURA', 'INGRESO', 'EGRESO', 'RETIRO', 'CIERRE', 'AJUSTE');

-- =========================================================
-- TABLA: categorias
-- =========================================================
-- Almacena las categorías usadas para clasificar productos.
CREATE TABLE categorias (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    CONSTRAINT uk_categorias_nombre UNIQUE (nombre)
);

-- Optimiza las búsquedas por nombre de categoría.
CREATE INDEX idx_categorias_nombre
    ON categorias (nombre);

-- =========================================================
-- TABLA: canales_venta
-- =========================================================
-- Registra los canales de venta disponibles para los productos.
CREATE TABLE canales_venta (
    id_canal_venta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    CONSTRAINT uk_canales_venta_nombre UNIQUE (nombre)
);

-- Mejora el rendimiento en consultas por nombre de canal.
CREATE INDEX idx_canales_venta_nombre
    ON canales_venta (nombre);

-- =========================================================
-- TABLA: usuarios
-- =========================================================
-- Guarda los usuarios del sistema, incluyendo sus credenciales y rol.
CREATE TABLE usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    rol rol_usuario NOT NULL,
    CONSTRAINT uk_usuarios_username UNIQUE (username)
);

-- Acelera búsquedas por nombre de usuario.
CREATE INDEX idx_usuarios_username
    ON usuarios (username);

-- Facilita filtrados por rol de usuario.
CREATE INDEX idx_usuarios_rol
    ON usuarios (rol);


-- =========================================================
-- TABLA: cajas
-- =========================================================
-- Representa una sesión de caja abierta por un usuario.
CREATE TABLE cajas (
    id_caja INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    fecha_apertura TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_cierre TIMESTAMPTZ,
    monto_inicial NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    monto_final NUMERIC(10,2),
    saldo_esperado NUMERIC(10,2),
    estado estado_caja NOT NULL DEFAULT 'ABIERTA',

    CONSTRAINT fk_cajas_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios(id_usuario)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_cajas_monto_inicial
        CHECK (monto_inicial >= 0)
);

CREATE INDEX idx_cajas_usuario
    ON cajas (id_usuario);

CREATE INDEX idx_cajas_estado
    ON cajas (estado);

CREATE INDEX idx_cajas_fecha_apertura
    ON cajas (fecha_apertura);


-- =========================================================
-- TABLA: productos
-- =========================================================
-- Almacena los productos del catálogo y sus precios.
CREATE TABLE productos (
    id_producto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria INTEGER NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    imagen VARCHAR(255),
    precio_minorista NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    precio_mayorista NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    cantidad_minima_mayorista INTEGER NOT NULL DEFAULT 0,
    activo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_productos_categoria
        FOREIGN KEY (id_categoria)
        REFERENCES categorias (id_categoria)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_productos_precio_minorista
        CHECK (precio_minorista >= 0),

    CONSTRAINT chk_productos_precio_mayorista
        CHECK (precio_mayorista >= 0),

    CONSTRAINT chk_productos_cantidad_minima_mayorista
        CHECK (cantidad_minima_mayorista >= 0)
);

-- Optimiza búsquedas por nombre de producto.
CREATE INDEX idx_productos_nombre
    ON productos (nombre);

-- Mejora el acceso por categoría asociada.
CREATE INDEX idx_productos_categoria
    ON productos (id_categoria);

-- =========================================================
-- TABLA: variantes_producto
-- =========================================================
-- Representa variantes de un producto, como SKU o código de barras.
CREATE TABLE variantes_producto (
    id_variante INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto INTEGER NOT NULL,
    codigo_barras VARCHAR(50),
    nombre_variante VARCHAR(100) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_variantes_producto_producto
        FOREIGN KEY (id_producto)
        REFERENCES productos (id_producto)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uk_variantes_producto_codigo_barras UNIQUE (codigo_barras)
);

-- Acelera consultas por producto padre.
CREATE INDEX idx_variantes_producto_producto
    ON variantes_producto (id_producto);

-- Optimiza búsquedas por código de barras.
CREATE INDEX idx_variantes_producto_codigo_barras
    ON variantes_producto (codigo_barras);

-- =========================================================
-- TABLA: productos_canales
-- =========================================================
-- Relaciona productos con canales de venta y define reglas de mayorista.
CREATE TABLE productos_canales (
    id_producto_canal INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto INTEGER NOT NULL,
    id_canal_venta INTEGER NOT NULL,
    limite_mayorista INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT fk_productos_canales_producto
        FOREIGN KEY (id_producto)
        REFERENCES productos (id_producto)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_productos_canales_canal
        FOREIGN KEY (id_canal_venta)
        REFERENCES canales_venta (id_canal_venta)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uk_productos_canales_producto_canal UNIQUE (id_producto, id_canal_venta),

    CONSTRAINT chk_productos_canales_limite_mayorista
        CHECK (limite_mayorista >= 0)
);

-- Optimiza búsquedas por producto asociado.
CREATE INDEX idx_productos_canales_producto
    ON productos_canales (id_producto);

-- Optimiza búsquedas por canal de venta asociado.
CREATE INDEX idx_productos_canales_canal
    ON productos_canales (id_canal_venta);

-- =========================================================
-- TABLA: stock
-- =========================================================
-- Controla el inventario disponible por variante y canal de venta.
CREATE TABLE stock (
    id_stock INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_variante INTEGER NOT NULL,
    id_canal_venta INTEGER NOT NULL,
    cantidad_disponible INTEGER NOT NULL DEFAULT 0,
    stock_minimo INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT fk_stock_variante
        FOREIGN KEY (id_variante)
        REFERENCES variantes_producto (id_variante)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_stock_canal
        FOREIGN KEY (id_canal_venta)
        REFERENCES canales_venta (id_canal_venta)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uk_stock_variante_canal UNIQUE (id_variante, id_canal_venta),

    CONSTRAINT chk_stock_cantidad_disponible
        CHECK (cantidad_disponible >= 0),

    CONSTRAINT chk_stock_minimo
        CHECK (stock_minimo >= 0)
);

-- Optimiza búsquedas por variante de producto.
CREATE INDEX idx_stock_variante
    ON stock (id_variante);

-- Optimiza búsquedas por canal de venta.
CREATE INDEX idx_stock_canal
    ON stock (id_canal_venta);

-- =========================================================
-- TABLA: ventas
-- =========================================================
-- Registra las ventas realizadas y su estado de proceso.
CREATE TABLE ventas (
    id_venta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_caja INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    fecha_hora TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    subtotal NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    descuento NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    total NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    estado estado_venta NOT NULL DEFAULT 'PENDIENTE',

    CONSTRAINT fk_ventas_caja
        FOREIGN KEY (id_caja)
        REFERENCES cajas (id_caja)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_ventas_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id_usuario)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_ventas_subtotal
        CHECK (subtotal >= 0),

    CONSTRAINT chk_ventas_descuento
        CHECK (descuento >= 0),

    CONSTRAINT chk_ventas_total
        CHECK (total >= 0)
);

CREATE INDEX idx_ventas_caja
    ON ventas (id_caja);

-- Optimiza filtros por fecha y hora de venta.
CREATE INDEX idx_ventas_fecha_hora
    ON ventas (fecha_hora);

-- Acelera consultas por usuario responsable de la venta.
CREATE INDEX idx_ventas_usuario
    ON ventas (id_usuario);

-- Facilita búsquedas por estado de la venta.
CREATE INDEX idx_ventas_estado
    ON ventas (estado);

-- =========================================================
-- TABLA: detalle_ventas
-- =========================================================
-- Guarda los productos incluidos en cada venta con su cantidad y precio.
CREATE TABLE detalle_ventas (
    id_detalle_venta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta INTEGER NOT NULL,
    id_variante INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    subtotal NUMERIC(10,2) NOT NULL DEFAULT 0.00,

    CONSTRAINT fk_detalle_ventas_venta
        FOREIGN KEY (id_venta)
        REFERENCES ventas (id_venta)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_detalle_ventas_variante
        FOREIGN KEY (id_variante)
        REFERENCES variantes_producto (id_variante)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_detalle_ventas_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT chk_detalle_ventas_precio_unitario
        CHECK (precio_unitario >= 0),

    CONSTRAINT chk_detalle_ventas_subtotal
        CHECK (subtotal >= 0)
);

-- Optimiza consultas por venta asociada.
CREATE INDEX idx_detalle_ventas_venta
    ON detalle_ventas (id_venta);

-- Optimiza consultas por variante vendida.
CREATE INDEX idx_detalle_ventas_variante
    ON detalle_ventas (id_variante);

-- =========================================================
-- TABLA: pagos
-- =========================================================
-- Registra los pagos asociados a cada venta.
CREATE TABLE pagos (
    id_pago INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta INTEGER NOT NULL,
    medio_pago medio_pago_enum NOT NULL,
    importe NUMERIC(10,2) NOT NULL DEFAULT 0.00,

    CONSTRAINT fk_pagos_venta
        FOREIGN KEY (id_venta)
        REFERENCES ventas (id_venta)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT chk_pagos_importe
        CHECK (importe >= 0)
);

-- Mejora el acceso por venta asociada.
CREATE INDEX idx_pagos_venta
    ON pagos (id_venta);

-- Facilita filtros por medio de pago.
CREATE INDEX idx_pagos_medio_pago
    ON pagos (medio_pago);


-- =========================================================
-- TABLA: movimientos_caja
-- =========================================================
-- Registra todos los movimientos monetarios realizados en una caja.
CREATE TABLE movimientos_caja (
    id_movimiento_caja INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_caja INTEGER NOT NULL,
    fecha_hora TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tipo_movimiento tipo_movimiento_caja_enum NOT NULL,
    importe NUMERIC(10,2) NOT NULL,

    CONSTRAINT fk_movimientos_caja_caja
        FOREIGN KEY (id_caja)
        REFERENCES cajas(id_caja)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE INDEX idx_movimientos_caja_caja
    ON movimientos_caja (id_caja);

CREATE INDEX idx_movimientos_caja_fecha_hora
    ON movimientos_caja (fecha_hora);

CREATE INDEX idx_movimientos_caja_tipo
    ON movimientos_caja (tipo_movimiento);


-- =========================================================
-- TABLA: movimientos_stock
-- =========================================================
-- Registra los cambios de inventario y su historial.
CREATE TABLE movimientos_stock (
    id_movimiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    id_stock INTEGER NOT NULL,
    fecha_hora TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tipo_movimiento tipo_movimiento_enum NOT NULL,
    cantidad INTEGER NOT NULL,
    stock_anterior INTEGER NOT NULL,
    stock_resultante INTEGER NOT NULL,
    motivo VARCHAR(255),

    CONSTRAINT fk_movimientos_stock_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id_usuario)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_movimientos_stock_stock
        FOREIGN KEY (id_stock)
        REFERENCES stock (id_stock)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_movimientos_stock_cantidad
        CHECK (cantidad > 0)
);

-- Optimiza consultas por fecha y hora del movimiento.
CREATE INDEX idx_movimientos_stock_fecha_hora
    ON movimientos_stock (fecha_hora);

-- Acelera búsquedas por usuario que realizó el movimiento.
CREATE INDEX idx_movimientos_stock_usuario
    ON movimientos_stock (id_usuario);

-- Mejora el acceso por stock asociado.
CREATE INDEX idx_movimientos_stock_stock
    ON movimientos_stock (id_stock);

-- Facilita filtros por tipo de movimiento.
CREATE INDEX idx_movimientos_stock_tipo_movimiento
    ON movimientos_stock (tipo_movimiento);